import type { ProPlayer } from "@/types/database"

export const demoPros: Partial<ProPlayer>[] = [
  { id: "p1", full_name: "Fan Zhendong", country: "🇨🇳 CHN", ittf_ranking: 1, ittf_points: 13000, play_style: "attacker", birth_year: 1997, club: "Guangdong, CHN", bio: "N°1 mondial, champion du monde 2019 et 2021. Jeu extrêmement complet et puissant.", image_url: null, equipment: { blade: "DHS Hurricane Long", rubber_fh: "DHS H3", rubber_bh: "DHS H8-80S" } },
  { id: "p2", full_name: "Wang Chuqin", country: "🇨🇳 CHN", ittf_ranking: 2, ittf_points: 12200, play_style: "attacker", birth_year: 2000, club: "Beijing, CHN", bio: "Jeune prodige chinois, champion olympique 2024.", image_url: null, equipment: { blade: "DHS Hurricane Long 5" } },
  { id: "p3", full_name: "Ma Long", country: "🇨🇳 CHN", ittf_ranking: 3, ittf_points: 11800, play_style: "allround", birth_year: 1988, club: "Liaoning, CHN", bio: "Légende du tennis de table, double champion olympique.", image_url: null },
  { id: "p4", full_name: "Truls Möregårdh", country: "🇸🇪 SWE", ittf_ranking: 4, ittf_points: 9800, play_style: "attacker", birth_year: 2000, club: "Ormesby TTC, GBR", bio: "Meilleur européen, finaliste olympique 2024.", image_url: null },
  { id: "p5", full_name: "Lim Jong-hoon", country: "🇰🇷 KOR", ittf_ranking: 5, ittf_points: 9200, play_style: "attacker", birth_year: 2000, club: "Samsung Life, KOR", bio: "Champion du monde junior.", image_url: null },
  { id: "p6", full_name: "Tomokazu Harimoto", country: "🇯🇵 JPN", ittf_ranking: 6, ittf_points: 9000, play_style: "attacker", birth_year: 2003, club: "T4 TTC, GER", bio: "Prodige japonais, plus jeune médaillé de l'histoire.", image_url: null, equipment: { blade: "Butterfly Harimoto Tomokazu Inner Force ALC" } },
  { id: "p7", full_name: "Félix Lebrun", country: "🇫🇷 FRA", ittf_ranking: 7, ittf_points: 8800, play_style: "attacker", birth_year: 2006, club: "Montpellier TT, FRA", bio: "Prodige français, médaillé olympique 2024 à 17 ans.", image_url: null },
  { id: "p8", full_name: "Darko Jorgic", country: "🇸🇮 SLO", ittf_ranking: 8, ittf_points: 8500, play_style: "allround", birth_year: 1998, club: "Borussia Düsseldorf, GER", bio: "Solide joueur européen.", image_url: null },
  { id: "p9", full_name: "Timo Boll", country: "🇩🇪 GER", ittf_ranking: 9, ittf_points: 8200, play_style: "allround", birth_year: 1981, club: "Borussia Düsseldorf, GER", bio: "Légende européenne, 6x champion d'Europe.", image_url: null, equipment: { blade: "Butterfly Timo Boll ALC", rubber_fh: "Butterfly Tenergy 05", rubber_bh: "Butterfly Tenergy 64" } },
  { id: "p10", full_name: "Hugo Calderano", country: "🇧🇷 BRA", ittf_ranking: 10, ittf_points: 7900, play_style: "attacker", birth_year: 1996, club: "Borussia Düsseldorf, GER", bio: "Meilleur joueur d'Amérique latine de l'histoire.", image_url: null },
  { id: "p11", full_name: "Alexis Lebrun", country: "🇫🇷 FRA", ittf_ranking: 11, ittf_points: 7600, play_style: "attacker", birth_year: 2004, club: "Pontoise-Cergy, FRA", bio: "Frère aîné de Félix, duo historique pour la France.", image_url: null },
  { id: "p12", full_name: "Benedikt Duda", country: "🇩🇪 GER", ittf_ranking: 12, ittf_points: 7300, play_style: "allround", birth_year: 1996, club: "1. FC Saarbrücken, GER", bio: "Solide joueur allemand.", image_url: null },
  { id: "p13", full_name: "Anton Källberg", country: "🇸🇪 SWE", ittf_ranking: 13, ittf_points: 7100, play_style: "attacker", birth_year: 1998, club: "Borussia Düsseldorf, GER", bio: "Talent suédois en pleine progression.", image_url: null },
  { id: "p14", full_name: "Simon Gauzy", country: "🇫🇷 FRA", ittf_ranking: 14, ittf_points: 6900, play_style: "attacker", birth_year: 1995, club: "Toulouse TT, FRA", bio: "Veteran de l'équipe de France.", image_url: null },
  { id: "p15", full_name: "Lin Yun-ju", country: "🇹🇼 TPE", ittf_ranking: 15, ittf_points: 6700, play_style: "attacker", birth_year: 2001, club: "T4 TTC, GER", bio: "Finaliste des JO 2020.", image_url: null },
]
